openapi: 3.0.0
info:
  title: Zoom Meeting API
  description: The Zoom Meeting APIs let developers to access information from Zoom.
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  contact:
    name: Zoom Developers
    url: https://developer.zoom.us/
  version: '2'
servers:
  - url: https://api.zoom.us/v2
paths:
  /live_meetings/{meetingId}/chat/messages/{messageId}:
    delete:
      tags:
        - Meetings
      summary: Delete a live meeting message
      description: >-
        Delete a message in a live meeting, based on ID. 


        **Prerequisites:** 

        * Have Zoom enable the DLP for the in-meeting chat feature to use this
        API.


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      operationId: deleteMeetingChatMessageById
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: [ ]
  /live_meetings/{meetingId}/events:
    patch:
      tags:
        - Meetings
      summary: Use in-meeting controls
      description: >-
        Control
        [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls)
        features. In-meeting controls include starting and stopping a recording,
        pausing and resuming a recording, and inviting participants. 


        **Note:** This API's recording control only works for cloud recordings.
        It does **not** work for local recordings. 


        **Prerequisites:**

        * The meeting **must** be a live meeting **except** inviting
        participants to the meeting through [call out (phone)/(room system)]. 

        * Recording control: [Cloud
        recording](https://support.zoom.us/hc/en-us/articles/360060231472-Enabling-cloud-recording)
        must be enabled on the account. 

        * The user calling this API must be the host or an alternative meeting
        host.
        
        
        
        **Scopes:** `meeting:write`,`meeting:write:admin`,`meeting:master`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      operationId: inMeetingControl
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
            - meeting:master
          openapi_authorization: [ ]
  /meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting
      description: >-
        Retrieve tha given meeting's details. 
        
        
        
        
        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      operationId: meeting
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: [ ]
    delete:
      tags:
        - Meetings
      summary: Delete a meeting
      description: >-
        Delete a meeting.  
        
        
        
        
        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      operationId: meetingDelete
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: [ ]
    patch:
      tags:
        - Meetings
      summary: Update a meeting
      description: >-
        Update meeting details.


        **Note** 

        * This API has a rate limit of **100 requests per day**. You can update
        a meeting for a maximum of **100 times within a 24-hour period**. 

        * The `start_time` value **must** be a future date. If the value is
        omitted or a date in the past, the API ignores this value and does
        **not** update any recurring meetings. 

        * The `recurrence` object is **required**.




        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      operationId: meetingUpdate
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: [ ]
      x-permissions:
        - User:Edit
      x-macro-scopes:
        - meeting:write
        - meeting:write:admin
  /users/{userId}/meetings:
    post:
      tags:
        - Meetings
      summary: Create a meeting
      description: >-
        [Create a
        meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)
        for a user. For user-level apps, pass [the `me`
        value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the
        `userId` parameter.


        * A meeting's `start_url` value is the URL a host or an alternative host
        can use to start a meeting. The expiration time for the `start_url`
        value is **two hours** for all regular users.

        * For `custCreate` meeting hosts (users created with the `custCreate`
        parameter via the [**Create
        users**](/api-reference/zoom-api/methods#operation/userCreate) API), the
        expiration time of the `start_url` parameter is **90 days** from the
        generation of the `start_url`.


        **Note:**


        For security reasons, the recommended way to programmatically get the
        updated `start_url` value after expiry is to call the [**Get a
        meeting**](/api-reference/zoom-api/methods#operation/meeting) API. Refer
        to the `start_url` value in the response.

         **100 requests per day**. The rate limit is applied against the `userId` of the **meeting host** used to make the request.

        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      operationId: meetingCreate
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      x-permissions:
        - User:Edit
      x-macro-scopes:
        - meeting:write
        - meeting:write:admin
      x-granular-scopes:
        - meeting:write:meeting
        - meeting:write:meeting:admin
components: