{
 "openapi": "3.0.0",
 "info": {
  "title": "Zoom Meeting API",
  "description": "The Zoom Meeting APIs let developers to access information from Zoom.",
  "termsOfService": "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
  "contact": {
   "name": "Zoom Developers",
   "url": "https://developer.zoom.us/"
  },
  "version": "2"
 },
 "servers": [
  {
   "url": "https://api.zoom.us/v2"
  }
 ],
 "paths": {
  "/accounts/{accountId}/lock_settings": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get locked settings",
    "description": "Retrieve an account's locked settings. \n\n Account admins and account owners can use [Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) to toggle settings on or off for all users in their account. \n\n\n**Note:** You can use Account Locked Settings with accounts that have master and sub accounts enabled.   \n   \n \n**Prerequisites:**\n* Pro or a higher paid account.   \n \n\n\n\n**Scopes:** `account:read:admin`\n\n**[Rate Limit Label](https://[...]",
    "operationId": "getAccountLockSettings",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Accounts"
    ],
    "summary": "Update locked settings",
    "description": "Update an account's locked settings.\n\n[Account Locked Settings](https://support.zoom.us/hc/en-us/articles/115005269866) allows account admins and account owners to toggle settings on or off for all users in your account.  \n\n**Note:** Yout must have a Pro or a higher plan and enabled master and sub accounts options.  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher paid account.   \n \n\n\n\n**Scopes:** `account:write:admin`\n\n**[Rate Limit Label](https://marketplace.[...]",
    "operationId": "UpdateLockedSettings",
    "security": [
     {
      "openapi_oauth": [
       "account:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountProfile:Edit",
      "AccountSetting:Edit"
     ],
     "x-macro-scopes": [
      "account:write:admin"
     ]
    }
   }
  },
  "/accounts/{accountId}/managed_domains": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get account's managed domains",
    "description": "Retrieve a list of an account's [managed domains](https://support.zoom.us/hc/en-us/articles/203395207). To get the master account's managed domains, pass the `me` value for the `accountId` path parameter. \n\n **Prerequisites:** \n* A Pro or a higher paid account with the Master account option enabled.\n\n**Scopes:** `account:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "accountManagedDomain",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin"
     ]
    }
   }
  },
  "/accounts/{accountId}/owner": {
   "put": {
    "tags": [
     "Accounts"
    ],
    "summary": "Update the account owner",
    "description": "Change an account's owner.\n\nAn account's current owner can [change the account's owner](https://support.zoom.us/hc/en-us/articles/115005686983-Change-Account-Owner) to another user on the same account.\n\n**Prerequisites:** \n* An account owner or admin permissions of an account \n* The account making this API request must be on a Pro or a higher account plan with [Master account](https://developers.zoom.us/docs/api/rest/master-account-apis/) privileges\n\n**[Rate Limit Lab[...]",
    "operationId": "UpdateTheAccountOwner",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": []
    }
   }
  },
  "/accounts/{accountId}/settings": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get account settings",
    "description": "Get an account's settings. \n\nTo get settings for a master account, use the `me` value for the `accountId` path parameter. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n**Scopes:** `account:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "accountSettings",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Accounts"
    ],
    "summary": "Update account settings",
    "description": "Update an account's settings. \nTo update the settings for a master account, pass the `me` value for the `accountId` path parameter. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n**Scopes:** `account:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "accountSettingsUpdate",
    "security": [
     {
      "openapi_oauth": [
       "account:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountProfile:Edit",
      "AccountSetting:Edit"
     ],
     "x-macro-scopes": [
      "account:write:admin"
     ]
    }
   }
  },
  "/accounts/{accountId}/settings/registration": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get an account's webinar registration settings",
    "description": "Get an account's webinar registration settings. To get the master account's webinar registration settings, use the `me` value for the `accountId` path parameter. \n\n**Prerequisites:** \n* The account must be a paid account.\n\n**Scopes:** `account:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "accountSettingsRegistration",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Accounts"
    ],
    "summary": "Update an account's webinar registration settings",
    "description": "Update an account's webinar registration settings. To update the master account's webinar registration settings, pass the `me` value for the `accountId` path parameter. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n**Scopes:** `account:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "accountSettingsRegistrationUpdate",
    "security": [
     {
      "openapi_oauth": [
       "account:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountProfile:Edit",
      "AccountSetting:Edit"
     ],
     "x-macro-scopes": [
      "account:write:admin"
     ]
    }
   }
  },
  "/accounts/{accountId}/settings/virtual_backgrounds": {
   "post": {
    "tags": [
     "Accounts"
    ],
    "summary": "Upload virtual background files",
    "description": "[Upload virtual background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE) for all users on the account to use. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**Scopes:** `account:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-refere[...]",
    "operationId": "uploadVB",
    "security": [
     {
      "openapi_oauth": [
       "account:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountProfile:Edit",
      "AccountSetting:Edit"
     ],
     "x-macro-scopes": [
      "account:write:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Accounts"
    ],
    "summary": "Delete virtual background files",
    "description": "Delete an account's existing virtual background files. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**Scopes:** `account:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "delVB",
    "security": [
     {
      "openapi_oauth": [
       "account:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountProfile:Edit",
      "AccountSetting:Edit"
     ],
     "x-macro-scopes": [
      "account:write:admin"
     ]
    }
   }
  },
  "/accounts/{accountId}/trusted_domains": {
   "get": {
    "tags": [
     "Accounts"
    ],
    "summary": "Get account's trusted domains",
    "description": "Retrieve an account's [trusted domains](https://support.zoom.us/hc/en-us/articles/203395207). To get the master account's trusted domains, use the `me` value for the `accountId` path parameter. \n\n **Prerequisites:** \n* The account must be a paid account.\n\n**Scopes:** `account:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "accountTrustedDomain",
    "security": [
     {
      "openapi_oauth": [
       "account:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "AccountSetting:Read"
     ],
     "x-macro-scopes": [
      "account:read:admin"
     ]
    }
   }
  },
  "/app/notifications": {
   "post": {
    "tags": [
     "Apps"
    ],
    "summary": "Send app notifications",
    "description": "Send app notifications to the Zoom \"Activity Center\". (Note: This API only supports OAuth 2.0.)\n\n**Scopes:** `app:notification:read`,`app:notification:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "Sendappnotifications",
    "security": [
     {
      "openapi_oauth": [
       "app:notification:read",
       "app:notification:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "app:notification:read",
      "app:notification:write"
     ]
    }
   }
  },
  "/zoomapp/deeplink": {
   "post": {
    "tags": [
     "Apps"
    ],
    "summary": "Generate an app deeplink",
    "description": "Create an app deeplink. \n\n \n\n**Scopes:** `app:deeplink:write`,`app:deeplink:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "generateAppDeeplink",
    "security": [
     {
      "openapi_oauth": [
       "app:deeplink:write",
       "app:deeplink:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "app:deeplink:write",
      "app:deeplink:write:admin"
     ]
    }
   }
  },
  "/archive_files": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "List archived files",
    "description": "Get an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA or other compliance requirements. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405[...]",
    "operationId": "listArchivedFiles",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Recording:Read"
     ],
     "x-macro-scopes": [
      "recording:read:admin"
     ]
    }
   }
  },
  "/archive_files/statistics": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "Get archived file statistics",
    "description": "Get statistics about an account's archived meeting or webinar files. \n\n Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA and other compliance requirements. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/e[...]",
    "operationId": "getArchivedFileStatistics",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:read:admin"
     ]
    }
   }
  },
  "/archive_files/{fileId}": {
   "patch": {
    "tags": [
     "Archiving"
    ],
    "summary": "Update an archived file's auto-delete status",
    "description": "Update an archived file's auto-delete status. \n\n **Prerequisites:** \n* [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) must enable the [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) for your account.\n* Open the disabling auto-delete feature in OP. Contact [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to open.\n\n**Scopes:** `recording:write`[...]",
    "operationId": "updateArchivedFile",
    "security": [
     {
      "openapi_oauth": [
       "recording:write",
       "recording:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Recording:Edit"
     ],
     "x-macro-scopes": [
      "recording:write",
      "recording:write:admin"
     ]
    }
   }
  },
  "/past_meetings/{meetingUUID}/archive_files": {
   "get": {
    "tags": [
     "Archiving"
    ],
    "summary": "Get a meeting's archived files",
    "description": "Return a specific meeting instance's [archived files](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators). \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\n**Scopes:** `recording:read`\n\n**[Rate Limit Label](https://marketplace.zoom.[...]",
    "operationId": "getArchivedFiles",
    "security": [
     {
      "openapi_oauth": [
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "recording:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "Archiving"
    ],
    "summary": "Delete a meeting's archived files",
    "description": "Use this API to delete all of a meeting's archived files. \n\n **Prerequisites:** \n* The [**Meeting and Webinar Archiving** feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars) enabled for your account by [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003).\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**[...]",
    "operationId": "deleteArchivedFiles",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Get meeting recordings",
    "description": "Returns all of a meeting's [recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording#h_7420acb5-1897-4061-87b4-5b76e99c03b4).\n\n Use the `download_url` property listed in the response to download the recording files.  To access a passcode-protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer token in the Authorization header. \n \n Example:  `curl -H 'Authorization: Bearer <ACCE[...]",
    "operationId": "recordingGet",
    "security": [
     {
      "openapi_oauth": [
       "recording:read",
       "phone_recording:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "recording:read",
      "phone_recording:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Delete meeting recordings",
    "description": "Delete all recording files of a meeting.  \n   \n \n\n**Prerequisites**:\n* Cloud Recording should be enabled on the user's account.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "recordingDelete",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/analytics_details": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Get Meeting Recording's Analytics Details",
    "description": "Use this API to return a meeting recording's [analytics details](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration: 1 Month**. To access a password-protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer token in the Authorization header. For example, \n\n `curl -H &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot[...]",
    "operationId": "analytics_details",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/analytics_summary": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Get Meeting Recording's Analytics Summary",
    "description": "Use this API to return a meeting recording's [analytics summary](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163). **Maximum duration: 1 Month**. To access a password-protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer token in the Authorization header. For example, \n\n `curl -H &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot[...]",
    "operationId": "analytics_summary",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/registrants": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "List recording registrants",
    "description": "Use this API to list registrants of a past meeting's [on-demand cloud recordings](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-recordings). Users must [register](/docs/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view the recordings. \n\n \n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRecordingRegistrants",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   },
   "post": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Create a recording registrant",
    "description": "Cloud Recordings of past Zoom Meetings can be made [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings). Users should be [registered](/docs/api-reference/zoom-api/methods#operation/meetingRecordingRegistrantCreate) to view these recordings.\n\nUse this API to register a user to gain access to **On-demand Cloud Recordings** of a past meeting.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://mark[...]",
    "operationId": "meetingRecordingRegistrantCreate",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/registrants/questions": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Get registration questions",
    "description": "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\nUse this API to retrieve a list of questions that are displayed for users to complete when registering to view the recording of a specific meeting.  \n \n\n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate Limit Label](https://marketpl[...]",
    "operationId": "recordingRegistrantsQuestionsGet",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   },
   "patch": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Update registration questions",
    "description": "For [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) meeting recordings, you can include fields with questions that will be shown to registrants when they register to view the recording.\n\nUse this API to update registration questions that are to be answered by users while registering to view a recording.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-referen[...]",
    "operationId": "recordingRegistrantQuestionUpdate",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/registrants/status": {
   "put": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Update registrant's status",
    "description": "A registrant can either be approved or denied from viewing the [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings) recording. \nUse this API to update a registrant's status.\n\n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRecordingRegistrantStatus",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/settings": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Get meeting recording settings",
    "description": "Retrieves settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).  \n   \n \n\n\n**Scopes:** `recording:read:admin`,`recording:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "recordingSettingUpdate",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   },
   "patch": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Update meeting recording settings",
    "description": "Updates settings applied to a meeting's [Cloud Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).      \n\n**Scopes:** `recording:write`,`recording:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "recordingSettingsUpdate",
    "security": [
     {
      "openapi_oauth": [
       "recording:write",
       "recording:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "recording:write",
      "recording:write:admin"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/{recordingId}": {
   "delete": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Delete a meeting recording file",
    "description": "Delete a specific recording file from a meeting.&lt;p style=&quot;background-color:#e1f5fe; color:#01579b; padding:8px&quot;&gt; &lt;b&gt;Note:&lt;/b&gt; To use this API, you must enable the &lt;b&gt;The host can delete cloud recordings&lt;/b&gt; setting. You can find this setting in the &lt;b&gt;Recording&lt;/b&gt; tab of the &lt;b&gt;Settings&lt;/b&gt; interface in the [Zoom web portal](https://zoom.us/).&lt;/p&gt;\n\n\n\n**Scopes:** `recording:write:admin`,`recording:write[...]",
    "operationId": "recordingDeleteOne",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/recordings/{recordingId}/status": {
   "put": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Recover a single recording",
    "description": "Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover a single recording file from the meeting.  \n \n\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "recordingStatusUpdateOne",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/meetings/{meetingUUID}/recordings/status": {
   "put": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "Recover meeting recordings",
    "description": "Zoom allows users to recover recordings from trash for up to 30 days from the deletion date. Use this API to recover all deleted [Cloud Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) of a specific meeting.  \n   \n \n**Prerequisites**:  \n \n* A Pro user with Cloud Recording enabled.\n\n**Scopes:** `recording:write:admin`,`recording:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Ligh[...]",
    "operationId": "recordingStatusUpdate",
    "security": [
     {
      "openapi_oauth": [
       "recording:write:admin",
       "recording:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "recording:write:admin",
      "recording:write"
     ]
    }
   }
  },
  "/users/{userId}/recordings": {
   "get": {
    "tags": [
     "Cloud Recording"
    ],
    "summary": "List all recordings",
    "description": "Lists all [cloud recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording) for a user.  \n\nFor user-level apps, pass the [`me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.  To access a user's passcode protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a bearer token in the authorization header.  \n\nExample:  `curl[...]",
    "operationId": "recordingsList",
    "security": [
     {
      "openapi_oauth": [
       "recording:read:admin",
       "recording:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Recording:Read"
     ],
     "x-macro-scopes": [
      "recording:read:admin",
      "recording:read"
     ]
    }
   }
  },
  "/contacts/groups": {
   "get": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "List contact groups",
    "description": "List [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**Scopes:** `contact_group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "contactGroups",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Create a contact group",
    "description": "Use this API to create a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupCreate",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   }
  },
  "/contacts/groups/{groupId}": {
   "get": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Get a contact group",
    "description": "Get a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "contactGroup",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Delete a contact group",
    "description": "Use this API to delete a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupDelete",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Update a contact group",
    "description": "Update a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupUpdate",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   }
  },
  "/contacts/groups/{groupId}/members": {
   "get": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "List contact group members",
    "description": "List members in [contact groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**Scopes:** `contact_group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "contactGroupMembers",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Add contact group members",
    "description": "Use this API to add members to a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupMemberAdd",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Contact Groups"
    ],
    "summary": "Remove members in a contact group",
    "description": "Use this API to remove members in a [contact group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).\n\n**Prerequisite**: Pro or higher account.  \n \n\n**Scopes:** `contact_group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "contactGroupMemberRemove",
    "security": [
     {
      "openapi_oauth": [
       "contact_group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "contact_group:write:admin"
     ]
    }
   }
  },
  "/metrics/chat": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get chat metrics",
    "description": "Get [metrics](https://support.zoom.us/hc/en-us/articles/204654719-Dashboard#h_cc7e9749-1c70-4afb-a9a2-9680654821e4) for how users are utilizing Zoom Chat to send messages.\n\nUse the `from` and `to` query parameters to specify a monthly date range for the dashboard data. The monthly date range must be within the last six months.\n\n&gt; **Note:** To query chat metrics from July 1, 2021 and later, use this endpoint instead of the [**Get IM metrics**](/docs/api-reference/zoom-a[...]",
    "operationId": "dashboardChat",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_im:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_im:read:admin"
     ]
    }
   }
  },
  "/metrics/client/feedback": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List Zoom meetings client feedback",
    "description": "Use this API to return [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf) survey results. You can specify a monthly date range for the Dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Prerequisites:** \n* A Business or higher account. \n* The &quot;[**Feedback to Zoom**](https://support.zoom.us/hc/en-us/ar[...]",
    "operationId": "dashboardClientFeedback",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_home:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_home:read:admin"
     ]
    }
   }
  },
  "/metrics/client/feedback/{feedbackId}": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get zoom meetings client feedback",
    "description": "Retrieve detailed information on a [Zoom meetings client feedback](https://support.zoom.us/hc/en-us/articles/115005855266-End-of-Meeting-Feedback-Survey#h_e30d552b-6d8e-4e0a-a588-9ca8180c4dbf).   \n  You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.\n\n**Prerequisites:**\n* Business or higher account\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/1150058380[...]",
    "operationId": "dashboardClientFeedbackDetail",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_home:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_home:read:admin"
     ]
    }
   }
  },
  "/metrics/client/satisfaction": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List client meeting satisfaction",
    "description": "If the [End of Meeting Feedback Survey](https://support.zoom.us/hc/en-us/articles/115005855266) option is enabled, attendees will be prompted with a survey window where they can tap either the **Thumbs Up** or **Thumbs Down** button that indicates their Zoom meeting experience. With this API, you can get information on the attendees' meeting satisfaction. Specify a monthly date range for the query using the from and to query parameters. The month should fall within the last s[...]",
    "operationId": "listMeetingSatisfaction",
    "security": [
     {
      "openapi_oauth": [
       "dashboard:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard:read:admin"
     ]
    }
   }
  },
  "/metrics/client_versions": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List the client versions",
    "description": "Use this API to list all the client versions and its count. \n\n **Prerequisites:** \n* A Business or a higher plan.\n\n**Scopes:** `dashboard:read:admin,dashboard_home:read:admin,zms:dashboard:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "getClientVersions",
    "security": [
     {
      "openapi_oauth": [
       "dashboard:read:admin,dashboard_home:read:admin,zms:dashboard:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard:read:admin,dashboard_home:read:admin,zms:dashboard:read"
     ]
    }
   }
  },
  "/metrics/crc": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get CRC port usage",
    "description": "A Cloud Room Connector allows H.323/SIP endpoints to connect to a Zoom meeting. \n\nUse this API to get the hour by hour CRC Port usage for a specified period of time. &lt;aside class='notice'&gt;We will provide the report for a maximum of one month. For example, if &quot;from&quot; is set to &quot;2017-08-05&quot; and &quot;to&quot; is set to &quot;2017-10-10&quot;, we will adjust &quot;from&quot; to &quot;2017-09-10&quot;.&lt;/aside&gt;  \n   \n \n**Prerequisites:**  \n \n*[...]",
    "operationId": "dashboardCRC",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_crc:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_crc:read:admin"
     ]
    }
   }
  },
  "/metrics/issues/zoomrooms": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get top 25 Zoom Rooms with issues",
    "description": "Get information on top 25 Zoom Rooms with issues in a month. The month specified with the &quot;from&quot; and &quot;to&quot; range should fall within the last six months.  \n \n**Prerequisites:**  \n \n* Business or a higher plan.\n* Zoom Room must be enabled in the account.\n\n**Scopes:** `dashboard_home:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardIssueZoomRoom",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_home:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_home:read:admin"
     ]
    }
   }
  },
  "/metrics/issues/zoomrooms/{zoomroomId}": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get issues of Zoom Rooms",
    "description": "Use this API to return information about the Zoom Rooms in an account with issues, such as disconnected hardware or bandwidth issues. You can specify a monthly date range for the Dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Prerequisites:** \n* A Business or a higher plan. \n* A Zoom Room must be enabled in the account.\n\n**Scopes:** `dashboard_home:read:admin`\n\n**[Rate Limit Label](https://marketplace.z[...]",
    "operationId": "dashboardIssueDetailZoomRoom",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_home:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_home:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List meetings",
    "description": "Lists total live or past meetings that occurred during a specified period of time. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.  \n  You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.  \n \n**Prerequisites:**   \n \n* Business or a highe[...]",
    "operationId": "dashboardMeetings",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin",
       "dashboard:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "DashboardMeetings:Read"
     ],
     "x-macro-scopes": [
      "dashboard_meetings:read:admin",
      "dashboard:read:admin"
     ],
     "x-granular-scopes": [
      "dashboard:read:list_meetings:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get meeting details",
    "description": "Get details on live or past meetings. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.  \n  You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.    \n \n**Prerequisites:**   \n \n* Business or a higher plan.\n\n**Scopes:** `dashboard_meetings:[...]",
    "operationId": "dashboardMeetingDetail",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}/participants": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List meeting participants",
    "description": "Return a list of participants from live or past meetings. \n\n If you do not provide the `type` query parameter, the default value will be set to the `live` value. This API will only return metrics for participants in a live meeting, if any exist. You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. \n\n**Note:** \n\nThis API may return empty values for participants' `user_nam[...]",
    "operationId": "dashboardMeetingParticipants",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}/participants/qos": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List meeting participants QoS",
    "description": "Show a list of meeting participants from live or past meetings, and their quality of service received during the meeting. The data returned indicates the connection quality for sending or receiving video, audio, and shared content. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API. \n* Does **not** have a signed HIPAA business associate agreement (BAA). \n* Is a [[...]",
    "operationId": "dashboardMeetingParticipantsQOS",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "DashboardMeetings:Read"
     ],
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}/participants/satisfaction": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get post meeting feedback",
    "description": "When a meeting ends, each attendee will be prompted to share their meeting experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific meeting. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API request[...]",
    "operationId": "participantFeedback",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}/participants/sharing": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get meeting sharing/recording details",
    "description": "Retrieve the sharing and recording details of participants from live or past meetings.  \n \n**Prerequisites:**   \n \n* Business or a higher plan.\n\n**Scopes:** `dashboard_meetings:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardMeetingParticipantShare",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/meetings/{meetingId}/participants/{participantId}/qos": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get meeting participant QoS",
    "description": "Return the quality of service (QoS) report for participants from live or past meetings. The data returned indicates the connection quality for sending/receiving video, audio, and shared content. The API returns this data for either the API request or when the API request was last received. \n\nWhen the sender sends data, a timestamp is attached to the sender's data packet. The receiver then returns this timestamp to the sender. This helps determine the upstream and downstream[...]",
    "operationId": "dashboardMeetingParticipantQOS",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_meetings:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "DashboardMeetings:Read"
     ],
     "x-macro-scopes": [
      "dashboard_meetings:read:admin"
     ]
    }
   }
  },
  "/metrics/quality": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get meeting quality scores",
    "description": "Use this API to return [meeting quality score](https://support.zoom.us/hc/en-us/articles/360061244651-Meeting-quality-scores-and-network-alerts-on-Dashboard) information. Meeting quality scores are based on the mean opinion score (MOS). The MOS measures a meeting's quality on a scale of &quot;Good&quot; (5-4), &quot;Fair&quot; (4-3), &quot;Poor&quot; (3-2), or &quot;Bad&quot; (2-1). \n\n**Prerequisites:** \n* A Business or a higher plan.\n\n**Scopes:** `dashboard_home:read:ad[...]",
    "operationId": "dashboardQuality",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_home:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_home:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List webinars",
    "description": "List all the live or past webinars from a specified period of time.   \n   \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Webinar add-on.\n\n\n\n\n**Scopes:** `dashboard_webinars:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`",
    "operationId": "dashboardWebinars",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get webinar details",
    "description": "Retrieve details from live or past webinars.  \n   \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Webinar add-on.\n\n\n\n**Scopes:** `dashboard_webinars:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardWebinarDetail",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}/participants": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get webinar participants",
    "description": "Return information about participants from live or past webinars. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business associate agreement (BAA). \n* Is a [**legacy** HIPAA BAA account](/docs/api-reference/other-references/legacy-business-associate-agreements). \n* Displays data for any users who are **not** part of the [...]",
    "operationId": "dashboardWebinarParticipants",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}/participants/qos": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List webinar participant QoS",
    "description": "Show a list of webinar participants from live or past webinars and the quality of service they received during the webinar. The data returned indicates the connection quality for sending/receiving video, audio, and shared content. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business associate agreement (BAA). \n* Is a [*[...]",
    "operationId": "dashboardWebinarParticipantsQOS",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "DashboardWebinars:Read"
     ],
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}/participants/satisfaction": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get post webinar feedback",
    "description": "When a Webinar ends, each attendee will be prompted to share their Webinar experience by clicking either thumbs up or thumbs down. Use this API to retrieve the feedback submitted for a specific webinar. Note that this API only works for meetings scheduled after December 20, 2020.\n\n**Prerequisites:**\n* [Feedback to Zoom](https://support.zoom.us/hc/en-us/articles/115005838023) setting must be enabled by the participant prior to the meeting.\n* The user making the API request[...]",
    "operationId": "participantWebinarFeedback",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}/participants/sharing": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get webinar sharing/recording details",
    "description": "Retrieve the sharing and recording details of participants from live or past webinars.   \n   \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Webinar add-on.\n\n\n\n**Scopes:** `dashboard_webinars:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardWebinarParticipantShare",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/webinars/{webinarId}/participants/{participantId}/qos": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get webinar participant QoS",
    "description": "Return the quality of service (QoS) for participants during live or past webinars. This data returned indicates the connection quality for sending/receiving video, audio, and shared content. The API returns this data for either the API request or when the API request was last received. \n\nWhen the sender sends its data, a timestamp is attached to the sender's data packet. The receiver then returns this timestamp to the sender. This helps determine the upstream and downstream[...]",
    "operationId": "dashboardWebinarParticipantQOS",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_webinars:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "DashboardWebinars:Read"
     ],
     "x-macro-scopes": [
      "dashboard_webinars:read:admin"
     ]
    }
   }
  },
  "/metrics/zoomrooms": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "List Zoom Rooms",
    "description": "List information on all Zoom Rooms in an account.  \n   \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Zoom Rooms set up.\n\n\n\n\n**Scopes:** `dashboard_zr:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`",
    "operationId": "dashboardZoomRooms",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_zr:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_zr:read:admin"
     ]
    }
   }
  },
  "/metrics/zoomrooms/issues": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get top 25 issues of Zoom Rooms",
    "description": "Get top 25 issues of Zoom Rooms.  \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Zoom Rooms set up.\n\n\n\n**Scopes:** `dashboard_zr:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardZoomRoomIssue",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_zr:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_zr:read:admin"
     ]
    }
   }
  },
  "/metrics/zoomrooms/{zoomroomId}": {
   "get": {
    "tags": [
     "Dashboards"
    ],
    "summary": "Get Zoom Rooms details",
    "description": "The Zoom Rooms dashboard metrics lets you know the type of configuration a Zoom room has and details on the meetings held in that room. \n\nUse this API to retrieve information on a specific room.  \n   \n \n**Prerequisites:**  \n \n* Business, Education or API Plan with Zoom Rooms set up.\n\n\n**Scopes:** `dashboard_zr:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "dashboardZoomRoom",
    "security": [
     {
      "openapi_oauth": [
       "dashboard_zr:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "dashboard_zr:read:admin"
     ]
    }
   }
  },
  "/devices": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "List devices",
    "description": "This API lets you list devices. \n\n\n\n**Scopes:** `device:read:admin`,`device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "listDevices",
    "security": [
     {
      "openapi_oauth": [
       "device:read:admin",
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "ZoomRooms:Read",
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "device:read:admin",
      "device:write:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Devices"
    ],
    "summary": "Add new device",
    "description": "This Device API lets you add a new device to Zoom Account. \n\n**Scope:** `device:write:admin`   \n \n **[Rate Limit Label](https://developers.zoom.us/docs/api/rest/rate-limits/):** `Medium`\n\n**Scopes:** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "addDevice",
    "security": [
     {
      "openapi_oauth": [
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "device:write:admin"
     ]
    }
   }
  },
  "/devices/{deviceId}": {
   "get": {
    "tags": [
     "Devices"
    ],
    "summary": "Get device detail",
    "description": "Retrieve a device's details.\n\n**Scopes:** `device:read:admin`,`device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "getDevice",
    "security": [
     {
      "openapi_oauth": [
       "device:read:admin",
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "ZoomRooms:Read",
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "device:read:admin",
      "device:write:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Devices"
    ],
    "summary": "Delete device",
    "description": "Delete a device from a Zoom account. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD (Zoom Device Management)\n\n**Scopes:** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "deleteDevice",
    "security": [
     {
      "openapi_oauth": [
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "MobileDeviceManagement:Edit"
     ],
     "x-macro-scopes": [
      "device:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Devices"
    ],
    "summary": "Change device ",
    "description": "Change device name. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD (Zoom Device Management)\n\n**Scopes:** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "updateDevice",
    "security": [
     {
      "openapi_oauth": [
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "ZoomRooms:Edit"
     ],
     "x-macro-scopes": [
      "device:write:admin"
     ]
    }
   }
  },
  "/devices/{deviceId}/assignment": {
   "patch": {
    "tags": [
     "Devices"
    ],
    "summary": "Change device association",
    "description": "This Device API lets you change device association from one Zoom Room to another. \n\n**Prerequisites:**\n* Device must be enrolled in ZMD (Zoom Device Management) \n\n\n\n**Scopes:** `device:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "changeDeviceAssociation",
    "security": [
     {
      "openapi_oauth": [
       "device:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "device:write:admin"
     ]
    }
   }
  },
  "/groups": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "List groups",
    "description": "List [groups](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro or higher account.  \n \n\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groups",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "summary": "Create a group",
    "description": "Use this API to create a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management). You can add a **maximum** of 100 groups in one account per day, and a maximum of 5000 groups in one account.\n\nIf you enabled a new group via the user interface, you can also choose whether to display the group and set its privacy level.\n\n**Prerequisites**: \n* A Pro or higher account\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/[...]",
    "operationId": "groupCreate",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get a group",
    "description": "Get a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under an account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "group",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Groups"
    ],
    "summary": "Delete a group",
    "description": "Delete an entire [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). **Prerequisites:** * A Pro, Business, or Education account.\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "groupDelete",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Edit"
     ],
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update a group",
    "description": "Update a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "groupUpdate",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/admins": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "List group admins",
    "description": "Use this API to return a list of [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrators under your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupAdmins",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "summary": "Add group admins",
    "description": "Use this API to add administrators to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupAdminsCreate",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/admins/{userId}": {
   "delete": {
    "tags": [
     "Groups"
    ],
    "summary": "Delete a group admin",
    "description": "Use this API to remove a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) administrator in a Zoom account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "groupAdminsDelete",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/lock_settings": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get locked settings",
    "description": "Retrieve a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. \nIf you lock a setting, the group members will not be able to modify it individually. \n\n **Note:** The `force_pmi_jbh_password` field under meeting settings is to be deprecated on September 22, 2019. This field is replaced by another field that will provide the same functionality.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:[...]",
    "operationId": "getGroupLockSettings",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Read"
     ],
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update locked settings",
    "description": "Update a [group's](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) locked settings. If you lock a setting, the group members cannot modify it individually. \n\n **Note:** The `force_pmi_jbh_password` field under meeting settings is deprecated as of September 22, 2019. This field will be replaced by another field that will provide the same functionality.&lt;/p&gt;\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:write[...]",
    "operationId": "groupLockedSettings",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Edit"
     ],
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/members": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "List group members ",
    "description": "List the members of a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) under your account.\n\n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupMembers",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Groups"
    ],
    "summary": "Add group members",
    "description": "Use this API to add users to a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in your account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupMembersCreate",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/members/{memberId}": {
   "delete": {
    "tags": [
     "Groups"
    ],
    "summary": "Delete a group member",
    "description": "Use this API to remove a user from a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-) in an account.\n\n**Prerequisites:** \n* A Pro, Business, or Education account\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "groupMembersDelete",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update a group member",
    "description": "Use this API to perform either of the following tasks: \n* Remove a group member from one group and move them to a different group. \n* Set a user's primary group. By default, the primary group is the first group that user is added to.\n\nIf a user is a member of multiple groups, you can [assign the user a primary group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-#h_d07c7dcd-4fd8-485a-b5fe-a322e8d21c09). The user will use the primary group's settings[...]",
    "operationId": "updateAGroupMember",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/settings": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get a group's settings",
    "description": "Get settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "getGroupSettings",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Read"
     ],
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update a group's settings",
    "description": "Update settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n **Note:**The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality\n**Prerequisite**: Pro, Business, or Education account  \n  \n\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/ra[...]",
    "operationId": "updateGroupSettings",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Edit"
     ],
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/settings/registration": {
   "get": {
    "tags": [
     "Groups"
    ],
    "summary": "Get a group's webinar registration settings",
    "description": "Get webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-). \n**Prerequisite**: Pro, Business, or Education account  \n \n\n\n**Scopes:** `group:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "groupSettingsRegistration",
    "security": [
     {
      "openapi_oauth": [
       "group:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Groups"
    ],
    "summary": "Update a group's webinar registration settings",
    "description": "Update webinar registration settings for a [group](https://support.zoom.us/hc/en-us/articles/204519819-Group-Management-).&lt;p style=&quot;background-color:#FEEFB3; color:#9F6000&quot;&gt;  \n Note:&lt;/b&gt; The `force_pmi_jbh_password` field under meeting settings is planned to be deprecated on September 22, 2019. This field will be replaced by another field that will provide the same functionality.&lt;/p&gt;\n**Prerequisite**: Pro, Business, or Education account  \n  \n\n[...]",
    "operationId": "groupSettingsRegistrationUpdate",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/groups/{groupId}/settings/virtual_backgrounds": {
   "post": {
    "tags": [
     "Groups"
    ],
    "summary": "Upload Virtual Background files",
    "description": "Use this API to [upload Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE) for all users in a group to use. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/[...]",
    "operationId": "uploadGroupVB",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Edit"
     ],
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Groups"
    ],
    "summary": "Delete Virtual Background files",
    "description": "Use this API to delete a group's [Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_01EJF3YFEWGT8YA0ZJ079JEDQE). \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**Scopes:** `group:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-lim[...]",
    "operationId": "delGroupVB",
    "security": [
     {
      "openapi_oauth": [
       "group:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Group:Edit"
     ],
     "x-macro-scopes": [
      "group:write:admin"
     ]
    }
   }
  },
  "/h323/devices": {
   "get": {
    "tags": [
     "H323 Devices"
    ],
    "summary": "List H.323/SIP devices",
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to list all H.323/SIP Devices on a Zoom account.  \n   \n \n\n\n**Scopes:** `h323:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-[...]",
    "operationId": "deviceList",
    "security": [
     {
      "openapi_oauth": [
       "h323:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "h323:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "H323 Devices"
    ],
    "summary": "Create a H.323/SIP device",
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to add a H.323/SIP device to your Zoom account  \n   \n \n\n\n**Scopes:** `h323:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
    "operationId": "deviceCreate",
    "security": [
     {
      "openapi_oauth": [
       "h323:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "h323:write:admin"
     ]
    }
   }
  },
  "/h323/devices/{deviceId}": {
   "delete": {
    "tags": [
     "H323 Devices"
    ],
    "summary": "Delete a H.323/SIP device",
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to delete a H.323/SIP device from your Zoom account.  \n   \n \n\n\n**Scopes:** `h323:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
    "operationId": "deviceDelete",
    "security": [
     {
      "openapi_oauth": [
       "h323:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "h323:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "H323 Devices"
    ],
    "summary": "Update a H.323/SIP device",
    "description": "A H.323 or SIP device can make a video call to a [Room Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector) to join a Zoom cloud meeting. A Room Connector can also call out to a H.323 or SIP device to join a Zoom cloud meeting. Use this API to edit information of a H.323/SIP device from your Zoom account.  \n   \n \n\n\n**Scopes:** `h323:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference[...]",
    "operationId": "deviceUpdate",
    "security": [
     {
      "openapi_oauth": [
       "h323:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "h323:write:admin"
     ]
    }
   }
  },
  "/im/groups": {
   "get": {
    "tags": [
     "IM Groups"
    ],
    "summary": "List IM directory groups",
    "description": "List [IM directory groups](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).  \n   \n \n\n\n**Scopes:** `imgroup:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroups",
    "security": [
     {
      "openapi_oauth": [
       "imgroup:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "imgroup:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Create an IM directory group",
    "description": "Create an IM directory group under your account.  \n   \n \n\n\n**Scopes:** `imgroup:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupCreate",
    "security": [
     {
      "openapi_oauth": [
       "imgroup:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "imgroup:write:admin"
     ]
    }
   }
  },
  "/im/groups/{groupId}": {
   "get": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Retrieve an IM directory group",
    "description": "Retrieve an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.  \n   \n \nScopes: `imgroup:read:admin`  \n \n\n \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroup",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "extensions": {}
   },
   "delete": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Delete an IM directory group",
    "description": "Delete an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.  \n   \n \nScopes: `imgroup:write:admin`  \n \n \n \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupDelete",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "extensions": {}
   },
   "patch": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Update an IM directory group",
    "description": "Update an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under your account.  \n   \n \n\n\n**Scopes:** `imgroup:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupUpdate",
    "security": [
     {
      "openapi_oauth": [
       "imgroup:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "imgroup:write:admin"
     ]
    }
   }
  },
  "/im/groups/{groupId}/members": {
   "get": {
    "tags": [
     "IM Groups"
    ],
    "summary": "List IM directory group members",
    "description": "List the members of an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management).  \n   \n \n\n\n**Scopes:** `imgroup:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroupMembers",
    "security": [
     {
      "openapi_oauth": [
       "imgroup:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "imgroup:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Add IM directory group members",
    "description": "Add members to an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.  \n   \n \n\n\n**Scopes:** `imgroup:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "imGroupMembersCreate",
    "security": [
     {
      "openapi_oauth": [
       "imgroup:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "imgroup:write:admin"
     ]
    }
   }
  },
  "/im/groups/{groupId}/members/{memberId}": {
   "delete": {
    "tags": [
     "IM Groups"
    ],
    "summary": "Delete IM directory group member",
    "description": "Delete a member from an [IM directory group](https://support.zoom.us/hc/en-us/articles/203749815-IM-Management) under an account.  \n   \n \nScopes: `imgroup:write:admin`  \n \n \n \n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "imGroupMembersDelete",
    "security": [
     {
      "openapi_oauth": [],
      "openapi_authorization": []
     }
    ],
    "extensions": {}
   }
  },
  "/information_barriers/policies": {
   "get": {
    "tags": [
     "Information Barriers"
    ],
    "summary": "List information Barrier policies",
    "description": "Return a list of all [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policies and their information. \n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Information Barriers for your account.\n\n**Scopes:** `information_barriers:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "InformationBarriersList",
    "security": [
     {
      "openapi_oauth": [
       "information_barriers:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Informationbarriers:Read"
     ],
     "x-macro-scopes": [
      "information_barriers:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Information Barriers"
    ],
    "summary": "Create an Information Barrier policy",
    "description": "Create a new Information Barrier policy. [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) help customers control communication policies and meet regulatory requirements at scale. Use information barriers to prevent specific groups of users who possess sensitive information from communicating with others who should not know this information. \n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/ar[...]",
    "operationId": "InformationBarriersCreate",
    "security": [
     {
      "openapi_oauth": [
       "information_barriers:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Informationbarriers:Edit"
     ],
     "x-macro-scopes": [
      "information_barriers:write:admin"
     ]
    }
   }
  },
  "/information_barriers/policies/{policyId}": {
   "get": {
    "tags": [
     "Information Barriers"
    ],
    "summary": "Get an Information Barrier policy by ID",
    "description": "Return an [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy by its ID. \n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Information Barriers for your account.\n\n**Scopes:** `information_barriers:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "InformationBarriersGet",
    "security": [
     {
      "openapi_oauth": [
       "information_barriers:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Informationbarriers:Read"
     ],
     "x-macro-scopes": [
      "information_barriers:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Information Barriers"
    ],
    "summary": "Remove an Information Barrier policy",
    "description": "Remove an [Information Barrier](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy.\n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Information Barriers for your account.\n\n**Scopes:** `information_barriers:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "InformationBarriersDelete",
    "security": [
     {
      "openapi_oauth": [
       "information_barriers:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Informationbarriers:Edit"
     ],
     "x-macro-scopes": [
      "information_barriers:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Information Barriers"
    ],
    "summary": "Update an Information Barriers policy",
    "description": "Update an [Information Barriers](https://support.zoom.us/hc/en-us/articles/360040913711-Information-Barriers) policy.\n\n **Prerequisites:** \n* [Contact Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003) to enable Information Barriers for your account.\n\n**Scopes:** `information_barriers:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "InformationBarriersUpdate",
    "security": [
     {
      "openapi_oauth": [
       "information_barriers:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "Informationbarriers:Edit"
     ],
     "x-macro-scopes": [
      "information_barriers:write:admin"
     ]
    }
   }
  },
  "/live_meetings/{meetingId}/chat/messages/{messageId}": {
   "delete": {
    "tags": [
     "Meetings"
    ],
    "summary": "Delete a live meeting message",
    "description": "Delete a message in a live meeting, based on ID. \n\n**Prerequisites:** \n* Have Zoom enable the DLP for the in-meeting chat feature to use this API.\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteMeetingChatMessageById",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ]
    }
   }
  },
  "/live_meetings/{meetingId}/events": {
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Use in-meeting controls",
    "description": "Control [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls) features. In-meeting controls include starting and stopping a recording, pausing and resuming a recording, and inviting participants. \n\n**Note:** This API's recording control only works for cloud recordings. It does **not** work for local recordings. \n\n**Prerequisites:**\n* The meeting **must** be a live meeting **except** inviting participants to the meeting through [call out[...]",
    "operationId": "inMeetingControl",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin",
       "meeting:master"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin",
      "meeting:master"
     ]
    }
   }
  },
  "/meetings/{meetingId}": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting",
    "description": "Retrieve tha given meeting's details. \n \n \n\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "meeting",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Meetings"
    ],
    "summary": "Delete a meeting",
    "description": "Delete a meeting.  \n   \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingDelete",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   },
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update a meeting",
    "description": "Update meeting details.\n\n**Note** \n* This API has a rate limit of **100 requests per day**. You can update a meeting for a maximum of **100 times within a 24-hour period**. \n* The `start_time` value **must** be a future date. If the value is omitted or a date in the past, the API ignores this value and does **not** update any recurring meetings. \n* The `recurrence` object is **required**.\n\n\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\n**[Rate Limit Label](ht[...]",
    "operationId": "meetingUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ]
    }
   }
  },
  "/meetings/{meetingId}/batch_polls": {
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Perform batch poll creation",
    "description": "Polls allow the meeting host to survey attendees. Create batch [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](htt[...]",
    "operationId": "createBatchPolls",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/batch_registrants": {
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Perform batch registration",
    "description": "Register up to 30 registrants at once for a meeting that requires [registration](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).   \n \n\n**Prerequisites:**  \n \n* The meeting host must be a Licensed user.\n* The meeting must require registration and should be of type `2`, i.e., they should be scheduled meetings. Instant meetings and Recurring meetings are not supported by this API.  \n   \n \n\n\n**Scopes:** `meeting:write`,`meeting:write:adm[...]",
    "operationId": "addBatchRegistrants",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ]
    }
   }
  },
  "/meetings/{meetingId}/invitation": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get meeting invitation",
    "description": "Retrieve the meeting invitation note for a specific meeting.\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "meetingInvitation",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   }
  },
  "/meetings/{meetingId}/invite_links": {
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Create meeting's invite links",
    "description": "Create a batch of invitation links for a meeting.\n\n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingInviteLinksCreate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/jointoken/live_streaming": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting's join token for live streaming",
    "description": "Get a meeting's join token to allow live streaming. The join token allows a recording bot implemented using Zoom meeting SDK to connect to a Zoom meeting &quot;hosted by the issuer of the token&quot;, and can call the streaming method automatically. It supports both regular live streaming, and raw streaming. \n\n**Prerequisites:** \n* A Pro or higher plan for the meeting host. \n* The **Allow livestreaming of meetings** user setting enabled in the Zoom web portal.\n\n**Scopes[...]",
    "operationId": "meetingLiveStreamingJoinToken",
    "security": [
     {
      "openapi_oauth": [
       "meeting_token:read:admin:live_streaming",
       "meeting_token:read:live_streaming"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting_token:read:admin:live_streaming",
      "meeting_token:read:live_streaming"
     ]
    }
   }
  },
  "/meetings/{meetingId}/jointoken/local_archiving": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting's archive token for local archiving",
    "description": "Get a meeting's archive token to allow local archiving. The archive token allows a meeting SDK app or bot to get archive permission to access the meeting's raw audio and video media stream in real-time. \n\n**Prerequisites:** \n* A Pro or higher plan for the meeting host. \n* The **Archive meetings and webinars** account setting enabled in the Zoom web portal.\n\n**Scopes:** `meeting_token:read:admin:local_archiving`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/ap[...]",
    "operationId": "meetingLocalArchivingArchiveToken",
    "security": [
     {
      "openapi_oauth": [
       "meeting_token:read:admin:local_archiving"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting_token:read:admin:local_archiving"
     ]
    }
   }
  },
  "/meetings/{meetingId}/jointoken/local_recording": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting's join token for local recording",
    "description": "Get a meeting's join token to allow for local recording. The join token lets a recording bot implemented using Zoom Meeting SDK to connect to a Zoom meeting. The recording bot can then automatically start locally recording. This supports both regular and raw local recording types. \n\n**Prerequisites:** \n* The **Local recording** user setting enabled in the Zoom web portal.\n\n**Scopes:** `meeting_token:read:admin:local_recording`,`meeting_token:read:local_recording`\n\n**[R[...]",
    "operationId": "meetingLocalRecordingJoinToken",
    "security": [
     {
      "openapi_oauth": [
       "meeting_token:read:admin:local_recording",
       "meeting_token:read:local_recording"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting_token:read:admin:local_recording",
      "meeting_token:read:local_recording"
     ]
    }
   }
  },
  "/meetings/{meetingId}/livestream": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get livestream details",
    "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Get a meeting's livestream configuration details such as Stream URL, Stream Key and Page URL.  \n   \n \n**Prerequisites:**  \n \n* Meeting host must be a licensed user with a Pro or higher plan.  \n \n* Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/11[...]",
    "operationId": "getMeetingLiveStreamDetails",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   },
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update a livestream",
    "description": "Update a meeting's livestream information. Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform.\n\n**Prerequisites:** \n* Meeting host must have a Pro license.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingLiveStreamUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/livestream/status": {
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update Live Stream Status",
    "description": "Zoom allows users to [livestream a meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service) to a custom platform. Update the status of a meeting's livestream.  \n   \n \n**Prerequisites:**  \n \n* Meeting host must have a Pro license.  \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingLiveStreamStatusUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/polls": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List meeting polls",
    "description": "Polls allow the meeting host to survey attendees. List all [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) of a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limi[...]",
    "operationId": "meetingPolls",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   },
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Create a meeting poll",
    "description": "Polls allow the meeting host to survey attendees. Create a [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) for a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro** or higher plan.\n* Polling feature must be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://[...]",
    "operationId": "meetingPollCreate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/polls/{pollId}": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting poll",
    "description": "Polls allow the meeting host to survey attendees. Retrieve information about a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).  \n   \n \n\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingPollGet",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   },
   "put": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update a meeting poll",
    "description": "Polls allow the meeting host to survey attendees. Update information of a specific meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)  \n   \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingPollUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   },
   "delete": {
    "tags": [
     "Meetings"
    ],
    "summary": "Delete a meeting poll",
    "description": "Polls allow the meeting host to survey attendees. Delete a meeting [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).  \n \n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n* Polling feature should be enabled in the host's account.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/a[...]",
    "operationId": "meetingPollDelete",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/registrants": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List meeting registrants",
    "description": "A host or a user with admin permission can require [registration for a Zoom meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings). List users that have registered for a meeting.  \n   \n \n\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRegistrants",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   },
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Add a meeting registrant",
    "description": "Create and submit a user's registration to a meeting. See [Customizing webinar registration](https://support.zoom.us/hc/en-us/articles/202835649-Customizing-webinar-registration) for details on how to set the requirements for these fields. Note that there is a maximum limit of 4,999 registrants per meeting and users will see an error if the meeting's capacity is reached. \n\n **Prerequisites:** \n* The host must be a **Licensed** user type.\n\n**Scopes:** `meeting:write:admin[...]",
    "operationId": "meetingRegistrantCreate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/registrants/questions": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List registration questions ",
    "description": "List registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).  \n \n\n\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingRegistrantsQuestionsGet",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update registration questions",
    "description": "Update registration questions that will be displayed to users while [registering for a meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).  \n   \n \n\n\n**Scopes:** `meeting:write`,`meeting:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingRegistrantQuestionUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ]
    }
   }
  },
  "/meetings/{meetingId}/registrants/status": {
   "put": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update registrant's status",
    "description": "Update a meeting registrant's status by either approving, cancelling or denying a registrant from joining the meeting.  \n   \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingRegistrantStatus",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/registrants/{registrantId}": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting registrant",
    "description": "Retrieve details on a specific user who has registered for the meeting. A host or a user with administrative permissions can require [registration for Zoom meetings](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).\n\n**Prerequisites:** \n* The account must have a Meeting plan\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingRegistrantGet",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "Meetings"
    ],
    "summary": "Delete a meeting registrant",
    "description": "Delete a meeting registrant.  \n   \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingregistrantdelete",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/sip_dialing": {
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting SIP URI with Passcode",
    "description": "Get a meeting's SIP URI.  The URI consists of the meeting ID, (optional, user-supplied) passcode and participant identifier code.  The API return data also includes additional fields to indicate whether the API caller has a valid Cloud Room Connector subscription, the participant identifier code from the URI, and the SIP URI validity period (in seconds). \n\n\n\n**Scopes:** `meeting:write:sip_dialing`,`meeting:write:admin:sip_dialing`\n\n**[Rate Limit Label](https://marketpla[...]",
    "operationId": "getSipDialingWithPasscode",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:sip_dialing",
       "meeting:write:admin:sip_dialing"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:sip_dialing",
      "meeting:write:admin:sip_dialing"
     ]
    }
   }
  },
  "/meetings/{meetingId}/status": {
   "put": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update meeting status",
    "description": "Update the status of a meeting.  \n   \n \n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "meetingStatus",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/survey": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get a meeting survey",
    "description": "Display information about a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host has a **Pro** license. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled on the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**Scopes:** `meeting:read`,`meeting:re[...]",
    "operationId": "meetingSurveyGet",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Meetings"
    ],
    "summary": "Delete a meeting survey",
    "description": "Delete a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). \n\n **Prerequisites:** \n* The host must be a **Pro** user type. \n* The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature enabled in the host's account. \n* The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**Scopes:** `meeting:write`,`meeting:write:a[...]",
    "operationId": "meetingSurveyDelete",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Meetings"
    ],
    "summary": "Update a meeting survey",
    "description": "Update a [meeting survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting).  **Prerequisites:** * The host must be a **Pro** user type. * The [**Meeting Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys) feature is enabled in the host's account. * The meeting must be a scheduled meeting. Instant meetings do not have survey features enabled.\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n[...]",
    "operationId": "meetingSurveyUpdate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/meetings/{meetingId}/token": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get meeting's token",
    "description": "Get a meeting's [closed caption token (caption URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service). This token lets you use a third-party service to stream text to their closed captioning software to the Zoom meeting. \n\n**Prerequisites:** \n* The **Closed captioning** setting enabled in the Zoom web portal. \n* The **Allow use of caption API Token to integrate with 3rd-party Closed Captioning services** setting enabled[...]",
    "operationId": "meetingToken",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   }
  },
  "/past_meetings/{meetingId}": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get past meeting details",
    "description": "Get information about a past meeting. \n\n \n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "pastMeetingDetails",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   }
  },
  "/past_meetings/{meetingId}/instances": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List past meeting instances",
    "description": "Return a list of past meeting instances. \n\n \n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "pastMeetings",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   }
  },
  "/past_meetings/{meetingId}/participants": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "Get past meeting participants",
    "description": "Retrieve information on participants from a past meeting. Note the API doesn't return results if there's only one participant in a meeting.  \n   \n \n**Prerequisites:**  \n \n* Paid account on a Pro or higher plan.\n\n  \n    \n   **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.\n\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
    "operationId": "pastMeetingParticipants",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   }
  },
  "/past_meetings/{meetingId}/polls": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List past meeting's poll results",
    "description": "[Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) allow the meeting host to survey attendees. List poll results of a meeting.  \n   \n \n\n**Prerequisites**:  \n \n* Host user type must be **Pro**.\n* Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.\n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medi[...]",
    "operationId": "listPastMeetingPolls",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   }
  },
  "/past_meetings/{meetingId}/qa": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List past meetings' Q&A",
    "description": "The question &amp; answer (Q&amp;A) feature for Zoom Meetings lets attendees ask questions during a meeting and lets the other attendees answer those questions.  \n \nList Q&amp;A of a specific meeting.\n\n**Prerequisites:**  \n \n* \n\n**Scopes:** `meeting:read:admin`,`meeting:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listPastMeetingQA",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read:admin",
       "meeting:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read:admin",
      "meeting:read"
     ]
    }
   }
  },
  "/users/{userId}/meeting_templates": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List meeting templates",
    "description": "List available [meeting templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates) for a user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `meeting:read`,`meeting:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listMeetingTemplates",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Create a meeting template from an existing meeting",
    "description": "Create a meeting template from an existing meeting. \n\n\n\n**Scopes:** `meeting:write:admin`,`meeting:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "meetingTemplateCreate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write:admin",
       "meeting:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:write:admin",
      "meeting:write"
     ]
    }
   }
  },
  "/users/{userId}/meetings": {
   "get": {
    "tags": [
     "Meetings"
    ],
    "summary": "List meetings",
    "description": "List a meeting host user's scheduled meetings. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n**Note** \n* This API **only** supports scheduled meetings. This API does not return information about instant meetings. \n* This API only returns a user's [unexpired meetings](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e84[...]",
    "operationId": "meetings",
    "security": [
     {
      "openapi_oauth": [
       "meeting:read",
       "meeting:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "meeting:read",
      "meeting:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Meetings"
    ],
    "summary": "Create a meeting",
    "description": "[Create a meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings) for a user. For user-level apps, pass [the `me` value](/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n* A meeting's `start_url` value is the URL a host or an alternative host can use to start a meeting. The expiration time for the `start_url` value is **two hours** for all regular users.\n* For `custCreate` meeting hosts (users created with the `c[...]",
    "operationId": "meetingCreate",
    "security": [
     {
      "openapi_oauth": [
       "meeting:write",
       "meeting:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "meeting:write",
      "meeting:write:admin"
     ],
     "x-granular-scopes": [
      "meeting:write:meeting",
      "meeting:write:meeting:admin"
     ]
    }
   }
  },
  "/users/{userId}/pac": {
   "get": {
    "tags": [
     "PAC"
    ],
    "summary": "List a user's PAC accounts",
    "description": "Retrieve a list of a user's [personal audio conference (PAC)](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) accounts. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n PAC allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only. \n\n **Prerequisites** \n* A Pro or higher plan with an [A[...]",
    "operationId": "userPACs",
    "security": [
     {
      "openapi_oauth": [
       "pac:read:admin",
       "pac:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "pac:read:admin",
      "pac:read"
     ]
    }
   }
  },
  "/report/activities": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get sign In / sign out activity report",
    "description": "Retrieve a list of sign in / sign out activity logs [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports) of users under a Zoom account.  \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportSignInSignOutActivities",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/billing": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get billing reports",
    "description": "Get department billing reports of a Zoom account.\n\n**Prerequisites:**  \n \n* Pro or a higher account with Department Billing option enabled. Contact Zoom Support team for details.\n\n\n\n**Scopes:** `report:read:admin`,`report:master`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "getBillingReport",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin",
       "report:master"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin",
      "report:master"
     ]
    }
   }
  },
  "/report/billing/invoices": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get billing invoice reports",
    "description": "Get department billing invoices reports for a specific billing period. Provide the `billing_id` of the billing period for which you would like to retrieve the invoices for. This ID can be retrieved from **Get Billing Reports** API. \n\n**Prerequisites:**  \n \n* Pro or a higher account with Department Billing option enabled. Contact the Zoom Support team to enable this feature.\n\n\n\n**Scopes:** `report:read:admin`,`report:master`\n\n**[Rate Limit Label](https://marketplace.[...]",
    "operationId": "getBillingInvoicesReports",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin",
       "report:master"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin",
      "report:master"
     ]
    }
   }
  },
  "/report/cloud_recording": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get cloud recording usage report",
    "description": "Retrieve cloud recording usage report for a specified period. You can only get cloud recording reports that is one day earlier than the current date and for the most recent period of 6 months. The date gap between from and to dates should be smaller or equal to 30 days.   \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportCloudRecording",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/daily": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get daily usage report",
    "description": "Retrieve daily report to access the account-wide usage of Zoom services for each day in a given month. It lists the number of new users, meetings, participants, and meeting minutes.  \n \n**Prerequisites**  \n \n* Pro or higher plan.  \n \n\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportDaily",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/meetings/{meetingId}": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get meeting detail reports",
    "description": "Get a detailed report for a past meeting.   \n \n**Prerequisites:**  \n \n* Pro or a higher plan.  \n \n \n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportMeetingDetails",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/meetings/{meetingId}/participants": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get meeting participant reports",
    "description": "Return a report of a past meeting with two or more participants, including the host. To return a report for past meeting with only **one** participant, use the [**List meeting participants**](/docs/api-reference/zoom-api/ma#operation/dashboardMeetingParticipants) API. \n\n**Note:** \n\nThis API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: \n* Does **not** have a signed HIPAA business [...]",
    "operationId": "reportMeetingParticipants",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/meetings/{meetingId}/polls": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get meeting poll reports",
    "description": "Use this API to get a report of [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings) results for a past meeting. \n\n **Prerequisites:** \n* A Pro or a higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportMeetingPolls",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/meetings/{meetingId}/qa": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get meeting Q&A report",
    "description": "The question &amp; answer (Q&amp;A) feature for meetings lets attendees ask questions during the meeting and lets the other attendees answer their questions.\n\nUse this API to retrieve a report on question and answers from past meetings.   \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportMeetingQA",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/operationlogs": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get operation logs report",
    "description": "The [Operations Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs) report allows you to audit admin and user activity, such as adding a new user, changing account settings, and deleting recordings.  \n \nUse this API to retrieve operation logs report for a specified period of time.  \n \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#[...]",
    "operationId": "reportOperationLogs",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/telephone": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get telephone reports",
    "description": "The [telephone report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports) allows you to view who dialed into meetings via phone (Audio Conferencing or SIP Connected Audio) and which number they dialed into and other details. Use this API to get telephone report for a specified period of time.\n\n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limit[...]",
    "operationId": "reportTelephone",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/upcoming_events": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get upcoming events report",
    "description": "Use this API to list upcoming meeting and/or webinar events within a specified period of time. The report's time range is limited to one month.\n\n**Prerequisites:** \n* A Pro or higher plan\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportUpcomingEvents",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/users": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get active/inactive host reports",
    "description": "A user is considered to be an active host during the month specified in the &quot;from&quot; and &quot;to&quot; range, if the user has hosted at least one meeting during this period. If the user didn't host any meetings during this period, the user is considered to be inactive.  \n The Active Hosts report displays a list of meetings, participants, and meeting minutes for a specific time range, up to one month. The month should fall within the last six months.  \n The Inactive[...]",
    "operationId": "reportUsers",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/users/{userId}/meetings": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get meeting reports",
    "description": "Retrieve [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting) on past meetings and webinars for a specified time period. The time range for the report is limited to a month and the month must fall within the past six months.\n\nMeetings and webinars are returned only if they have two or more unique participants.    \n   \n \n**Prerequisites:**  \n \n* Pro or higher plan.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.[...]",
    "operationId": "reportMeetings",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/webinars/{webinarId}": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get webinar detail reports",
    "description": "Retrieve a [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting) containing past webinar details.    \n   \n \n**Prerequisites:**  \n \n* Pro or higher plan with Webinar add-on.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportWebinarDetails",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/webinars/{webinarId}/participants": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get webinar participant reports",
    "description": "Get a detailed report on each webinar attendee. You can get webinar participant reports for the last 6 months. \n\n **Prerequisites:** \n* A Pro or a higher plan with Webinar add-on enabled.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportWebinarParticipants",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/webinars/{webinarId}/polls": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get webinar poll reports",
    "description": "Retrieve a report on past [webinar polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).  \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar add-on enabled.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`",
    "operationId": "reportWebinarPolls",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/report/webinars/{webinarId}/qa": {
   "get": {
    "tags": [
     "Reports"
    ],
    "summary": "Get webinar Q&A report",
    "description": "The Question &amp; Answer (Q&amp;A) feature for webinars allows attendees to ask questions during the webinar and for the panelists, co-hosts and host to answer their questions.\n\nUse this API to retrieve a report on question and answers from past webinars.   \n   \n \n**Prerequisites:**  \n \n* Pro or a higher plan with Webinar add-on enabled.\n\n**Scopes:** `report:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):*[...]",
    "operationId": "reportWebinarQA",
    "security": [
     {
      "openapi_oauth": [
       "report:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "report:read:admin"
     ]
    }
   }
  },
  "/roles": {
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "List roles",
    "description": "List [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) on your account\n\n**Prerequisites** :\n*  Pro or higher plan. \n*  For setting the initial role, you must be the Account Owner. \n*  For subsequent role management, you must be the Account Owner or user with role management permissions.\n\n**Scopes:** `role:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "roles",
    "security": [
     {
      "openapi_oauth": [
       "role:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Roles"
    ],
    "summary": "Create a role",
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or member. \n\n**Pre-requisites**  \n \n* Pro or higher plan.\n* To set the initial role, you must be the account owner.  \n \n* For subsequent role management, you must be either the account owner or user with role management permissions.  \n \n\n\n**Scopes:** `role:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "createRole",
    "security": [
     {
      "openapi_oauth": [
       "role:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:write:admin"
     ]
    }
   }
  },
  "/roles/{roleId}": {
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "Get role information",
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or member. Account owners and users with edit privileges for role management can add customized roles with a list of privileges.\n\nUse this API to get information including specific privileges assigned to a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control).  \n \n**Pre-requisites**  \n \n* A Pro or higher plan.  \n \n* For role management and updates, you [...]",
    "operationId": "getRoleInformation",
    "security": [
     {
      "openapi_oauth": [
       "role:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Roles"
    ],
    "summary": "Delete a role",
    "description": "Each Zoom user automatically has a role which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.\n\nUse this API to delete a role.  \n \n**Pre-requisite:**  \n \n* A Pro or higher plan.  \n \n* For role management and updates, you must be the Account Owner or user with role management permissions.\n\n\n\n**Scopes:** `role:write:admin`\n\n**[Rate Limit Label](https://marketpla[...]",
    "operationId": "deleteRole",
    "security": [
     {
      "openapi_oauth": [
       "role:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Roles"
    ],
    "summary": "Update role information",
    "description": "Each Zoom user automatically has a [role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) which can either be owner, administrator, or a member. Account Owners and users with edit privileges for Role management can add customized roles with a list.\n\nUse this API to change the privileges, name and description of a specific role.  \n \n**Pre-requisite:**  \n \n* A Pro or higher plan.  \n \n* For role management and updates, you must be the Ac[...]",
    "operationId": "updateRole",
    "security": [
     {
      "openapi_oauth": [
       "role:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:write:admin"
     ]
    }
   }
  },
  "/roles/{roleId}/members": {
   "get": {
    "tags": [
     "Roles"
    ],
    "summary": "List members in a role",
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to list all the members that are assigned a specific role.\n\n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**Scopes:** `role:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "roleMembers",
    "security": [
     {
      "openapi_oauth": [
       "role:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Roles"
    ],
    "summary": "Assign a role",
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to [assign a role](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control#h_748b6fd8-5057-4cf4-bbfd-787909c09db0) to members.\n\n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**Scopes:** `role:write:admin`\n\n**[Rate Limit Label](https://mar[...]",
    "operationId": "AddRoleMembers",
    "security": [
     {
      "openapi_oauth": [
       "role:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:write:admin"
     ]
    }
   }
  },
  "/roles/{roleId}/members/{memberId}": {
   "delete": {
    "tags": [
     "Roles"
    ],
    "summary": "Unassign a role",
    "description": "User [roles](https://support.zoom.us/hc/en-us/articles/115001078646-Role-Based-Access-Control) can have a set of permissions that allows access only to the pages a user needs to view or edit. Use this API to unassign a user's role.\n\n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**Scopes:** `role:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "roleMemberDelete",
    "security": [
     {
      "openapi_oauth": [
       "role:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "role:write:admin"
     ]
    }
   }
  },
  "/sip_phones": {
   "get": {
    "tags": [
     "SIP Phone"
    ],
    "summary": "List SIP phones",
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to list SIP phones on an account.  \n   \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n* [...]",
    "operationId": "listSipPhones",
    "security": [
     {
      "openapi_oauth": [
       "sip_phone:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "sip_phone:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "SIP Phone"
    ],
    "summary": "Enable SIP phone",
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to enable a user to use SIP phone.  \n   \n \n**Prerequisites**:\n* Currently only supported on Cisco and Avaya PBX systems. \n*[...]",
    "operationId": "createSIPPhone",
    "security": [
     {
      "openapi_oauth": [
       "sip_phone:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "sip_phone:write:admin"
     ]
    }
   }
  },
  "/sip_phones/{phoneId}": {
   "delete": {
    "tags": [
     "SIP Phone"
    ],
    "summary": "Delete SIP phone",
    "description": "Use this API to delete a Zoom account's SIP phone. \n\n **Prerequisites**: \n* Currently only supported on Cisco and Avaya PBX systems. \n* The user must enable **SIP Phone Integration** by contacting the [Zoom Sales](https://zoom.us/contactsales) team.\n\n**Scopes:** `sip_phone:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "deleteSIPPhone",
    "security": [
     {
      "openapi_oauth": [
       "sip_phone:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "sip_phone:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "SIP Phone"
    ],
    "summary": "Update SIP phone",
    "description": "Zoom's Phone System Integration (PSI), also referred as SIP phones, enables an organization to leverage the Zoom client to complete a softphone registration to supported premise based PBX system. End users will have the ability to have softphone functionality within a single client while maintaining a comparable interface to Zoom Phone. Use this API to update information of a specific SIP Phone on a Zoom account.  \n   \n \n**Prerequisites**:\n* Currently only supported on Ci[...]",
    "operationId": "updateSIPPhone",
    "security": [
     {
      "openapi_oauth": [
       "sip_phone:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "sip_phone:write:admin"
     ]
    }
   }
  },
  "/tsp": {
   "get": {
    "tags": [
     "TSP"
    ],
    "summary": "Get account's TSP information",
    "description": "Get information on Telephony Service Provider on an account level.  \n   \n \n**Prerequisites:**  \n \n* A Pro or a higher plan.\n\n**Scopes:** `tsp:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "tsp",
    "security": [
     {
      "openapi_oauth": [
       "tsp:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:read:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "TSP"
    ],
    "summary": "Update account's TSP information",
    "description": "Update information of the Telephony Service Provider set up on an account.  \n \n**Prerequisites**:  \n \nTSP account option should be enabled.  \n \n\n\n**Scopes:** `tsp:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "tspUpdate",
    "security": [
     {
      "openapi_oauth": [
       "tsp:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:write:admin"
     ]
    }
   }
  },
  "/users/{userId}/tsp": {
   "get": {
    "tags": [
     "TSP"
    ],
    "summary": "List user's TSP accounts",
    "description": "A user can have a maximum of two TSP accounts. Use this API to list all TSP accounts of a user.  \n   \n \n\n\n**Scopes:** `tsp:read:admin`,`tsp:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userTSPs",
    "security": [
     {
      "openapi_oauth": [
       "tsp:read:admin",
       "tsp:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:read:admin",
      "tsp:read"
     ]
    }
   },
   "post": {
    "tags": [
     "TSP"
    ],
    "summary": "Add a user's TSP account",
    "description": "Add a user's TSP account.  \n   \n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userTSPCreate",
    "security": [
     {
      "openapi_oauth": [
       "tsp:write:admin",
       "tsp:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:write:admin",
      "tsp:write"
     ]
    }
   }
  },
  "/users/{userId}/tsp/settings": {
   "patch": {
    "tags": [
     "TSP"
    ],
    "summary": "Set global dial-in URL for a TSP user",
    "description": "A global dial-in page can provide a list of global access numbers using which audio conferencing can be conducted. By calling this API, you can set the url for the global dial-in page of a user whose Zoom account has TSP and special TSP with third-party audio conferencing options enabled. &lt;p&gt;&lt;/p&gt;\n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "tspUrlUpdate",
    "security": [
     {
      "openapi_oauth": [
       "tsp:write:admin",
       "tsp:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:write:admin",
      "tsp:write"
     ]
    }
   }
  },
  "/users/{userId}/tsp/{tspId}": {
   "get": {
    "tags": [
     "TSP"
    ],
    "summary": "Get a user's TSP account",
    "description": "Each user can have a maximum of two TSP accounts. Use this API to retrieve details of a specific TSP account enabled for a specific user.  \n   \n \n\n\n**Scopes:** `tsp:read:admin`,`tsp:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userTSP",
    "security": [
     {
      "openapi_oauth": [
       "tsp:read:admin",
       "tsp:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:read:admin",
      "tsp:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "TSP"
    ],
    "summary": "Delete a user's TSP account",
    "description": "Delete a user's TSP account.  \n   \n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userTSPDelete",
    "security": [
     {
      "openapi_oauth": [
       "tsp:write:admin",
       "tsp:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:write:admin",
      "tsp:write"
     ]
    }
   },
   "patch": {
    "tags": [
     "TSP"
    ],
    "summary": "Update a TSP account",
    "description": "Update a user's TSP account.  \n   \n \n\n\n**Scopes:** `tsp:write:admin`,`tsp:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userTSPUpdate",
    "security": [
     {
      "openapi_oauth": [
       "tsp:write:admin",
       "tsp:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tsp:write:admin",
      "tsp:write"
     ]
    }
   }
  },
  "/tracking_fields": {
   "get": {
    "tags": [
     "Tracking Field"
    ],
    "summary": "List tracking fields",
    "description": "Use this API to list all the [tracking fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields) on your Zoom account. Tracking fields let you analyze usage by various fields within an organization. \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**Scopes:** `tracking_fields:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "trackingfieldList",
    "security": [
     {
      "openapi_oauth": [
       "tracking_fields:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tracking_fields:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Tracking Field"
    ],
    "summary": "Create a tracking field",
    "description": "Use this API to create a new [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). Tracking fields let you analyze usage by various fields within an organization. When scheduling a meeting, tracking fields will be included in the meeting options. \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/[...]",
    "operationId": "trackingfieldCreate",
    "security": [
     {
      "openapi_oauth": [
       "tracking_fields:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tracking_fields:write:admin"
     ]
    }
   }
  },
  "/tracking_fields/{fieldId}": {
   "get": {
    "tags": [
     "Tracking Field"
    ],
    "summary": "Get a tracking field",
    "description": "Use this API to return information about a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**Scopes:** `tracking_fields:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "trackingfieldGet",
    "security": [
     {
      "openapi_oauth": [
       "tracking_fields:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tracking_fields:read:admin"
     ]
    }
   },
   "delete": {
    "tags": [
     "Tracking Field"
    ],
    "summary": "Delete a tracking field",
    "description": "Use this API to delete a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "trackingfieldDelete",
    "security": [
     {
      "openapi_oauth": [
       "tracking_fields:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tracking_fields:write:admin"
     ]
    }
   },
   "patch": {
    "tags": [
     "Tracking Field"
    ],
    "summary": "Update a tracking field",
    "description": "Use this API to update a [tracking field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). \n\n**Prerequisites:** \n* A Business, Education, API or higher plan.\n\n**Scopes:** `tracking_fields:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "trackingfieldUpdate",
    "security": [
     {
      "openapi_oauth": [
       "tracking_fields:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "tracking_fields:write:admin"
     ]
    }
   }
  },
  "/users": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "List users",
    "description": "Retrieve a list your account's users. \n\n\n\n**Scopes:** `user:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "users",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "user:read:admin"
     ]
    }
   },
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Create users",
    "description": "Add a new user to your Zoom account. \n\n**Note:** The following rate limits apply when you use the `create` value for the `action` field: \n* 50 requests per day for **Free** accounts. \n* 1,500 requests per day for **Pro** accounts. \n* 10,000 requests per day for **Business+** accounts. \n\n**Prerequisites:** \n* A Pro or higher plan.\n\n**Scopes:** `user:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`[...]",
    "operationId": "userCreate",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin"
     ]
    }
   }
  },
  "/users/email": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Check a user email",
    "description": "Verify if a user's email is registered with Zoom.  \n   \n \n\n&lt;b&gt;Note: &lt;/b&gt;You can successfully check if a user is a registered Zoom user only if the user **signed up for Zoom via email and is within your account.** If you provide an email address of a user who is not in your account, the value of &quot;existed_email&quot; parameter will be &quot;false&quot; irrespective of whether or not the user is registered with Zoom. The response of this API call will not in[...]",
    "operationId": "userEmail",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/features": {
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Bulk update feature",
    "description": "Bulk update features. \n\n\n\n**Scopes:** `user:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "bulkUpdateFeature",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "user:write:admin"
     ]
    }
   }
  },
  "/users/me/zak": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get the user's ZAK",
    "description": "Get the Zoom Access Key (ZAK) for the authenticated user associated with the access token in the API request. Use a ZAK to start or join a meeting on behalf of this user.\n\nZAKs obtained with this endpoint expire five minutes after receipt.\n\nTo get a ZAK for a different user or with a different expiration, use the [Get a user token](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#operation/userToken) API with the `zak` `type` query parameter.\n\nSee [Gettin[...]",
    "operationId": "userZak",
    "security": [
     {
      "openapi_oauth": [
       "user_zak:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user_zak:read"
     ]
    }
   }
  },
  "/users/summary": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get user summary",
    "description": "Use this API to get a summary of users, including the number and types of users in the account.\n\n \n\n**Scopes:** `user:read:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userSummary",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin"
     ]
    }
   }
  },
  "/users/vanity_name": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Check a user's PM room",
    "description": "A personal meeting room is a virtual meeting room that can be permanently assigned to a user.\nUse this API to check if a personal meeting room with the given name exists or not.  \n   \n \n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userVanityName",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/{userId}": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get a user",
    "description": "View a user's information on a Zoom account. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n**Note** Users who have not activated their account will have a `pending` status. These users' `created_at` timestamp will also display the time at which the API call was made, **not** the account's creation date. \n\n**Note:** The `user_info:read` scope is only available when y[...]",
    "operationId": "user",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read",
       "user_info:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "user:read:admin",
      "user:read",
      "user_info:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete a user",
    "description": "**Disassociate** (unlink) a user or permanently **delete** a user.  \n\n**Disassociating** a user unlinks the user from the associated Zoom account and provides the user their own basic free Zoom account. The disassociated user can then purchase their own Zoom licenses. An account owner or account admin can transfer the user's meetings, webinars, and cloud recordings to another user before disassociation.\n\n\n**Deleting** a user permanently removes the user and their data fr[...]",
    "operationId": "userDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   },
   "patch": {
    "tags": [
     "Users"
    ],
    "summary": "Update a user",
    "description": "Update a user's [Zoom profile](https://support.zoom.us/hc/en-us/articles/201363203-My-Profile) information. For user-level apps, pass [the `me` value](hhttps://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "userUpdate",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/assistants": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "List user assistants",
    "description": "List a user's assistants. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meetings on behalf of the current user, as well as manage and act as an alternative host for all meetings if the adm[...]",
    "operationId": "userAssistants",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   },
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Add assistants",
    "description": "Assign assistants to a user. In the request body, provide either the user's ID or the user's email address. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users to whom the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). Assistants can schedule meetings on behalf of the curren[...]",
    "operationId": "userAssistantCreate",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete user assistants",
    "description": "Delete all of the current user's assistants. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user, and manage and act as an alternative host for all meet[...]",
    "operationId": "userAssistantsDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/assistants/{assistantId}": {
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete a user assistant",
    "description": "Delete a specific assistant of a user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAssistants are the users who the current user has assigned [scheduling privilege](https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-Privilege). These assistants can schedule meeting on behalf of the current user as well as manage and act as an alternative host for all meet[...]",
    "operationId": "userAssistantDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/collaboration_devices": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "List a user's collaboration devices",
    "description": "List a user's collaboration devices. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "listCollaborationDevices",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/{userId}/collaboration_devices/{collaborationDeviceId}": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get collaboration device detail",
    "description": "Get collaboration device detail. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getCollaborationDevice",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/{userId}/email": {
   "put": {
    "tags": [
     "Users"
    ],
    "summary": "Update a user's email",
    "description": "Change a user's [email address](https://support.zoom.us/hc/en-us/articles/201362563-How-Do-I-Change-the-Email-on-My-Account-) on a Zoom account that has managed domain set up. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n* If the Zoom account in which the user belongs has multiple [managed domains](https://support.zoom.us/hc/en-us/articles/203395207-What-is-Managed-Do[...]",
    "operationId": "userEmailUpdate",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/meeting_templates/{meetingTemplateId}": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get meeting template detail",
    "description": "Retrieve a user's [meeting template](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates). For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "getUserMeetingTemplates",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/{userId}/password": {
   "put": {
    "tags": [
     "Users"
    ],
    "summary": "Update a user's password",
    "description": "Update the [password](https://support.zoom.us/hc/en-us/articles/206344385-Change-a-User-s-Password) of a user using which the user can login to Zoom. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAfter this request is processed successfully, an email notification is sent to the user saying that the password was changed.  \n \n**Prerequisites:**  \n \n* Owner or admin o[...]",
    "operationId": "userPassword",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/permissions": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get user permissions",
    "description": "Get permissions that have been granted to the user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nUsers can be assigned a set of permissions that allows them to access only the pages or information that a user needs to view or edit.\n\n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-l[...]",
    "operationId": "userPermission",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   }
  },
  "/users/{userId}/picture": {
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Upload a user's profile picture",
    "description": "Upload a user's profile picture. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nProvide `multipart/form-data` as the value of the `content-type` header for this request. This API supports `.jpeg` and `.png` file formats.\n\n\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `[...]",
    "operationId": "userPicture",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete a user's profile picture",
    "description": "Delete a user's profile picture. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`",
    "operationId": "userPictureDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/presence_status": {
   "put": {
    "tags": [
     "Users"
    ],
    "summary": "Update a user's presence status",
    "description": "Update a user's presence status. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nA user's status **cannot** be updated more than once per minute. For example, you can only submit a maximum of one update request per minute for a single user.\n\nUsers in the Zoom desktop client and mobile apps are assigned with a [presence status](https://support.zoom.us/hc/en-us/articles/[...]",
    "operationId": "updatePresenceStatus",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/schedulers": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "List user schedulers",
    "description": "List all of a user's schedulers. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers in this context are users who can schedule meetings for the current user. For example, if the current user, the user whose `userId` was passed in the `path` parameter, is **User A**, this API's response will list all users for whom **User A** can schedule and manage meetings. **Us[...]",
    "operationId": "userSchedulers",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete user schedulers",
    "description": "Delete all of a user's schedulers. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers are users on whose behalf the current user (assistant) can schedule meetings for. By calling this API, the current user will no longer be a scheduling assistant of any user. \n\n**Prerequisites:** \n* Current user (assistant) must be under the same account as the scheduler.\n\n*[...]",
    "operationId": "userSchedulersDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/schedulers/{schedulerId}": {
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete a scheduler",
    "description": "Delete a scheduler. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nSchedulers are users who the current user (assistant) can schedule meetings on their behalf. By calling this API, the current user will no longer be a scheduling assistant of this scheduler.\n\n**Prerequisites:** \n* Current user must be under the same account as the scheduler.\n\n**Scopes:** `user:write[...]",
    "operationId": "userSchedulerDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/settings": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get user settings",
    "description": "Retrieve a user's settings. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "userSettings",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   },
   "patch": {
    "tags": [
     "Users"
    ],
    "summary": "Update user settings",
    "description": "Update a user's settings. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\n\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "userSettingsUpdate",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/settings/virtual_backgrounds": {
   "post": {
    "tags": [
     "Users"
    ],
    "summary": "Upload Virtual Background files",
    "description": "Use this API to [upload a Virtual Background files](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background) to a user's profile. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Note:** \n* A user profile cannot exceed more than 10 Virtual Background files. \n* You can only upload image files that are in JPG/JPEG, GIF or PNG format. \n* Video files mus[...]",
    "operationId": "uploadVBuser",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Delete Virtual Background files",
    "description": "Use this API to delete a user's Virtual Background files. For user-level apps, pass [the `me` value](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#mekeyword) instead of the `userId` parameter. \n\n **Prerequisites:** \n* The [Virtual Background feature](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background#h_2ef28080-fce9-4ac2-b567-dc958afab1b7) must be enabled on the account.\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit La[...]",
    "operationId": "delUserVB",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Edit"
     ],
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/status": {
   "put": {
    "tags": [
     "Users"
    ],
    "summary": "Update user status",
    "description": "[Deactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_6a9bc1c3-d739-4945-b1f2-00b3b88fb5cc) an active user or to [reactivate](https://support.zoom.us/hc/en-us/articles/115005269946-Remove-User-from-your-Account#h_16319724-d120-4be6-af5d-31582d134ea0) a deactivated user. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAn accou[...]",
    "operationId": "userStatus",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/users/{userId}/token": {
   "get": {
    "tags": [
     "Users"
    ],
    "summary": "Get a user's token",
    "description": "Get a user's Zoom token or Zoom Access Key (ZAK). For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter. \n\n \n\n**Scopes:** `user:read:admin`,`user:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userToken",
    "security": [
     {
      "openapi_oauth": [
       "user:read:admin",
       "user:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:read:admin",
      "user:read"
     ]
    }
   },
   "delete": {
    "tags": [
     "Users"
    ],
    "summary": "Revoke a user's SSO token",
    "description": "Revoke a user's SSO token. For user-level apps, pass [the `me` value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword) instead of the `userId` parameter.\n\nAfter calling this API, the SSO user will be logged out of their current Zoom session.\n\n\n\n**Scopes:** `user:write:admin`,`user:write`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`",
    "operationId": "userSSOTokenDelete",
    "security": [
     {
      "openapi_oauth": [
       "user:write:admin",
       "user:write"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-macro-scopes": [
      "user:write:admin",
      "user:write"
     ]
    }
   }
  },
  "/live_webinars/{webinarId}/chat/messages/{messageId}": {
   "delete": {
    "tags": [
     "Webinars"
    ],
    "summary": "Delete a live webinar message",
    "description": "Deletes a message in a live webinar based on ID. \n\n**Prerequisites:** \n* Have Zoom enable the DLP for the in-meeting chat feature to use this API.\n\n**Scopes:** `webinar:write`,`webinar:write:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "deleteWebinarChatMessageById",
    "security": [
     {
      "openapi_oauth": [
       "webinar:write",
       "webinar:write:admin"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [],
     "x-macro-scopes": [
      "webinar:write",
      "webinar:write:admin"
     ]
    }
   }
  },
  "/past_webinars/{webinarId}/absentees": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "summary": "Get webinar absentees",
    "description": "List absentees of a webinar.  \n   \n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `HEAVY`",
    "operationId": "webinarAbsentees",
    "security": [
     {
      "openapi_oauth": [
       "webinar:read:admin",
       "webinar:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "webinar:read:admin",
      "webinar:read"
     ],
     "x-granular-scopes": [
      "webinar:read:list_absentees",
      "webinar:read:list_absentees:admin"
     ]
    }
   }
  },
  "/past_webinars/{webinarId}/instances": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "summary": "List past webinar instances",
    "description": "List past webinar instances.  \n   \n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
    "operationId": "pastWebinars",
    "security": [
     {
      "openapi_oauth": [
       "webinar:read:admin",
       "webinar:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "webinar:read:admin",
      "webinar:read"
     ],
     "x-granular-scopes": [
      "webinar:read:list_past_instances",
      "webinar:read:list_past_instances:admin"
     ]
    }
   }
  },
  "/past_webinars/{webinarId}/participants": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "summary": "List webinar participants",
    "description": "Retrieve a list of all the participants who attended a webinar hosted in the past. \n\n**Prerequisites:** \n* A Pro or higher plan with a webinar add-on.\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listWebinarParticipants",
    "security": [
     {
      "openapi_oauth": [
       "webinar:read:admin",
       "webinar:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "webinar:read:admin",
      "webinar:read"
     ],
     "x-granular-scopes": [
      "webinar:read:list_past_participants:admin",
      "webinar:read:list_past_participants"
     ]
    }
   }
  },
  "/past_webinars/{webinarId}/polls": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "summary": "List past webinar poll results",
    "description": "The polling feature for webinar lets you create single-choice or multiple-choice polling questions for your webinars. This API endpoint retrieves the results for webinar polls of a specific webinar.\n\n**Prerequisites:**  \n \n* [Webinar license](https://zoom.us/webinar)  \n \n\n\n**Scopes:** `webinar:read:admin`,`webinar:read`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `MEDIUM`",
    "operationId": "listPastWebinarPollResults",
    "security": [
     {
      "openapi_oauth": [
       "webinar:read:admin",
       "webinar:read"
      ],
      "openapi_authorization": []
     }
    ],
    "extensions": {
     "x-permissions": [
      "User:Read"
     ],
     "x-macro-scopes": [
      "webinar:read:admin",
      "webinar:read"
     ],
     "x-granular-scopes": [
      "webinar:read:list_past_polls",
      "webinar:read:list_past_polls:admin"
     ]
    }
   }
  },
  "/past_webinars/{webinarId}/qa": {
   "get": {
    "tags": [
     "Webinars"
    ],
    "summary": "List Q&As of a past webinar",
[...]
